# -*- coding: utf-8 -*-
"""Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnkufTLOb81_VZ-QgZawuCP3WVSWZtNs
"""

import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import FloatSlider, Button, HBox, VBox, Output, interactive

output = Output()

default_amplitude = 1.0
default_frequency = 1.0
default_phase = 0.0

amp_slider = FloatSlider(value=1.0, min=0.1, max=2.0, step=0.1, description='Amplitude')
freq_slider = FloatSlider(value=1.0, min=0.1, max=5.0, step=0.1, description='Frequency')
phase_slider = FloatSlider(value=0.0, min=0.0, max=2 * np.pi, step=0.1, description='Phase')
reset_button = Button(description="Reset", button_style='warning')

def update_plot(amplitude, frequency, phase):
    x = np.linspace(0, 10, 500)
    y = amplitude * np.sin(2 * np.pi * frequency * x + phase)
    with output:
        output.clear_output(wait=True)
        plt.figure(figsize=(8, 4))
        plt.plot(x, y, label=f'{amplitude} * sin(2π{frequency}x + {phase})')
        plt.legend()
        plt.grid()
        plt.show()

def reset_sliders(button):
    amp_slider.value = default_amplitude
    freq_slider.value = default_frequency
    phase_slider.value = default_phase

reset_button.on_click(reset_sliders)

interactive_plot = interactive(update_plot, amplitude=amp_slider, frequency=freq_slider, phase=phase_slider)

display(VBox([HBox([amp_slider, freq_slider, phase_slider, reset_button]), output]))
update_plot(1.0, 1.0, 0.0)